// Code generated by tools/lightagent-mirror. DO NOT EDIT.
//
// This is the subset of ReadyFleet's wire protocol that the BYOD light agent
// actually references. Declarations belonging to the managed venue fleet are
// deliberately absent: their absence is the point. If a command is not here,
// this agent has no code that can act on it.
//
// Regenerate from the ReadyFleet repository; never edit in place.

package proto

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

// ProtocolVersion is the wire protocol version. The server advertises the
// versions it understands in [HelloAckData]; the agent picks the highest
// match and pins it for the lifetime of the connection.
const ProtocolVersion = 1

// MessageType enumerates the wire-level message kinds.
type MessageType string

// Agent → Server.
const (
	MsgHello     MessageType = "hello"
	MsgPong      MessageType = "pong"
	MsgInventory MessageType = "inventory"
	MsgTelemetry MessageType = "telemetry"

	MsgResult MessageType = "result"
)

// Server → Agent.
const (
	MsgHelloAck       MessageType = "hello_ack"
	MsgPing           MessageType = "ping"
	MsgCommand        MessageType = "command"
	MsgCancel         MessageType = "cancel"
	MsgTerminalOpen   MessageType = "terminal_open"
	MsgTerminalInput  MessageType = "terminal_input"
	MsgTerminalResize MessageType = "terminal_resize"
	MsgTerminalClose  MessageType = "terminal_close"
	MsgScreenStart    MessageType = "screen_start"
	MsgScreenStop     MessageType = "screen_stop"
)

// CommandKind enumerates the operations the server can ask an agent to run.
// The kind selects the schema of the per-command Args.
type CommandKind string

const (
	CmdInventoryRefresh CommandKind = "inventory_refresh"
	CmdStartSolarbeam   CommandKind = "start_solarbeam"
	CmdStopSolarbeam    CommandKind = "stop_solarbeam"

	CmdUpdate CommandKind = "update"

	CmdSolarbeamEngineUpdate CommandKind = "solarbeam_engine_update"
	CmdShowNotification      CommandKind = "show_notification"
)

// Envelope wraps every message on the wire.
type Envelope struct {
	ID        uuid.UUID       `json:"id"`
	Type      MessageType     `json:"type"`
	InReplyTo *uuid.UUID      `json:"in_reply_to,omitempty"`
	Timestamp time.Time       `json:"ts"`
	Data      json.RawMessage `json:"data,omitempty"`
}

// NewEnvelope returns an envelope wrapping data, marshaled to JSON.
// id is generated if zero.
func NewEnvelope(t MessageType, id uuid.UUID, replyTo *uuid.UUID, data any) (Envelope, error) {
	if id == uuid.Nil {
		id = uuid.New()
	}
	var raw json.RawMessage
	if data != nil {
		b, err := json.Marshal(data)
		if err != nil {
			return Envelope{}, fmt.Errorf("proto: marshal data for %s: %w", t, err)
		}
		raw = b
	}
	return Envelope{
		ID:        id,
		Type:      t,
		InReplyTo: replyTo,
		Timestamp: time.Now().UTC(),
		Data:      raw,
	}, nil
}

// DecodeData unmarshals e.Data into v.
func (e Envelope) DecodeData(v any) error {
	if len(e.Data) == 0 {
		return fmt.Errorf("proto: envelope %s carries no data", e.Type)
	}
	if err := json.Unmarshal(e.Data, v); err != nil {
		return fmt.Errorf("proto: decode %s data: %w", e.Type, err)
	}
	return nil
}

// HelloData is the agent's introduction at the start of a connection.
// MachineID is informational; the authoritative identity is the CN of the
// presented client certificate, which the server cross-checks.
type HelloData struct {
	ProtocolVersion   int    `json:"protocol_version"`
	AgentVersion      string `json:"agent_version"`
	MachineID         string `json:"machine_id"`
	OS                string `json:"os"`
	OSVersion         string `json:"os_version"`
	InventoryChecksum string `json:"inventory_checksum,omitempty"`
}

// InventoryData is a full inventory snapshot. Sent on hello and in response
// to a CmdInventoryRefresh.
//
// Fields are intentionally generous in scope so we don't have to revise the
// envelope as new collectors land. Phase-3 fields (BootEntries) live in this
// same struct to avoid a schema fork.
type InventoryData struct {
	Hostname            string         `json:"hostname"`
	FQDN                string         `json:"fqdn,omitempty"`
	OS                  OSInfo         `json:"os"`
	Hardware            HardwareInfo   `json:"hardware"`
	Network             NetworkInfo    `json:"network"`
	InstalledSoftware   []SoftwareItem `json:"installed_software"`
	BootEntries         []BootEntry    `json:"boot_entries,omitempty"`
	HardwareFingerprint string         `json:"hardware_fingerprint,omitempty"`
	CollectedAt         time.Time      `json:"collected_at"`
	Checksum            string         `json:"checksum,omitempty"`
}

type OSInfo struct {
	Name        string    `json:"name"`
	Version     string    `json:"version"`
	Build       string    `json:"build,omitempty"`
	InstallDate time.Time `json:"install_date,omitempty"`
}

type HardwareInfo struct {
	CPUModel string     `json:"cpu_model"`
	CPUCores int        `json:"cpu_cores"`
	RAMBytes int64      `json:"ram_bytes"`
	Disks    []DiskInfo `json:"disks"`
}

type DiskInfo struct {
	Model     string `json:"model,omitempty"`
	SizeBytes int64  `json:"size_bytes"`
	FreeBytes int64  `json:"free_bytes,omitempty"`
	Mount     string `json:"mount,omitempty"`
}

type NetworkInfo struct {
	NICs      []NIC  `json:"nics"`
	PrimaryIP string `json:"primary_ip,omitempty"`
}

type NIC struct {
	Name    string   `json:"name"`
	MAC     string   `json:"mac"`
	IPs     []string `json:"ips"`
	Gateway string   `json:"gateway,omitempty"`
}

type SoftwareItem struct {
	Name        string    `json:"name"`
	Version     string    `json:"version,omitempty"`
	Publisher   string    `json:"publisher,omitempty"`
	InstallDate time.Time `json:"install_date,omitempty"`
}

type BootEntry struct {
	GUID        string `json:"guid"`
	Description string `json:"description"`
	IsDefault   bool   `json:"is_default"`
}

// TelemetryData is one point-in-time performance/thermal sample, pushed
// unsolicited by the agent on a fixed cadence (see agent/internal/telemetry).
// Sensor fields (Disks' throughput, GPUs, Thermal) are always best-effort:
// a board that doesn't expose a sensor simply omits that field rather than
// failing the whole sample.
type TelemetryData struct {
	CollectedAt   time.Time    `json:"collected_at"`
	CPUPercent    float64      `json:"cpu_percent"`
	RAMUsedBytes  int64        `json:"ram_used_bytes"`
	RAMTotalBytes int64        `json:"ram_total_bytes"`
	Disks         []DiskUsage  `json:"disks,omitempty"`
	Network       NetworkUsage `json:"network"`
	GPUs          []GPUInfo    `json:"gpus,omitempty"`
	Thermal       ThermalInfo  `json:"thermal,omitzero"`
}

// DiskUsage is one logical disk's current usage and throughput. ReadBytesSec/
// WriteBytesSec are 0 when the platform can't provide per-second throughput
// (still a valid sample — usage without throughput).
type DiskUsage struct {
	Mount         string `json:"mount"`
	UsedBytes     int64  `json:"used_bytes"`
	TotalBytes    int64  `json:"total_bytes"`
	ReadBytesSec  int64  `json:"read_bytes_sec,omitempty"`
	WriteBytesSec int64  `json:"write_bytes_sec,omitempty"`
}

// NetworkUsage is fleet-wide (summed across NICs) throughput at CollectedAt.
type NetworkUsage struct {
	RxBytesSec int64 `json:"rx_bytes_sec"`
	TxBytesSec int64 `json:"tx_bytes_sec"`
}

// GPUInfo is one GPU's utilization/memory/temperature, read via the
// sensors helper. Pointer fields are nil when that sensor isn't available
// on this board — never a false zero.
type GPUInfo struct {
	Name          string   `json:"name"`
	UtilPercent   *float64 `json:"util_percent,omitempty"`
	MemUsedBytes  *int64   `json:"mem_used_bytes,omitempty"`
	MemTotalBytes *int64   `json:"mem_total_bytes,omitempty"`
	TempC         *float64 `json:"temp_c,omitempty"`
}

// ThermalInfo is best-effort non-GPU temperature data from the sensors
// helper. Both fields nil means the helper found no readable sensor on
// this board — a valid, common outcome, not an error.
type ThermalInfo struct {
	CPUTempC         *float64 `json:"cpu_temp_c,omitempty"`
	MotherboardTempC *float64 `json:"motherboard_temp_c,omitempty"`
}

// ResultData is the terminal message for a command.
type ResultData struct {
	ExitCode   int           `json:"exit_code"`
	Duration   time.Duration `json:"duration_ms,omitempty" swaggertype:"integer"`
	OutputHash string        `json:"output_hash,omitempty"`
	Error      string        `json:"error,omitempty"`
}

// HelloAckData carries any config the server wants the agent to honour for
// this connection.
type HelloAckData struct {
	AcceptedProtocolVersion int       `json:"accepted_protocol_version"`
	HeartbeatSeconds        int       `json:"heartbeat_seconds,omitempty"`
	OutputChunkBytes        int       `json:"output_chunk_bytes,omitempty"`
	NeedsInventory          bool      `json:"needs_inventory,omitempty"`
	ServerTime              time.Time `json:"server_time"`
}

// CommandData is a server-issued command. Args is shaped per Kind; see the
// per-kind structs below.
type CommandData struct {
	Kind CommandKind     `json:"kind"`
	Args json.RawMessage `json:"args"`
}

// DecodeArgs unmarshals c.Args into v.
func (c CommandData) DecodeArgs(v any) error {
	if len(c.Args) == 0 {
		return fmt.Errorf("proto: command %s has no args", c.Kind)
	}
	return json.Unmarshal(c.Args, v)
}

// SolarbeamStartArgs is the payload for CmdStartSolarbeam: everything the venue
// agent needs to launch the bridge + engine for one session. BundleToken is the
// single-use credential the bridge presents to ReadyApp's /venue/bundle.
type SolarbeamStartArgs struct {
	SessionID   string `json:"session_id"`
	MachineID   string `json:"machine_id"`
	ReadyappURL string `json:"readyapp_url"`
	BundleToken string `json:"bundle_token"`
}

// StopSolarbeamArgs is the payload for CmdStopSolarbeam: it tears down the
// session the agent set up for start_solarbeam — stops the service-managed
// engine and the agent-launched bridge, and clears the per-session bridge.env.
// SessionID identifies the session being torn down (for logging/audit; the
// agent stops the single local engine/bridge regardless).
type StopSolarbeamArgs struct {
	SessionID string `json:"session_id"`
}

// UpdateArgs is the payload for CmdUpdate. The agent downloads the stable URL,
// verifies the bytes against SHA256 (and, on Windows, the Authenticode
// signature), then swaps the binary and restarts the service. Version is the
// target semver, used for logs and post-restart confirmation. Expiring bearer
// credentials are never persisted in targets or command artifacts.
type UpdateArgs struct {
	// ReleaseID identifies the specific release being applied, independent
	// of Version (which is human-facing/log-facing). Mirrors
	// SolarbeamEngineUpdateArgs.ReleaseID.
	ReleaseID string `json:"release_id"`
	Version   string `json:"version"`
	URL       string `json:"url"`
	SHA256    string `json:"sha256"`
	// AgentProfile is the profile ("managed" or "byod_solarbeam") this
	// update is claimed to be for. Each entrypoint checks it against its
	// own hardcoded ProductPolicy so a compromised or confused controller
	// cannot talk one profile's agent into accepting an update meant for
	// the other.
	AgentProfile      string `json:"agent_profile"`
	SignerFingerprint string `json:"signer_fingerprint"`
	ProductID         string `json:"product_id"`
}

// SolarbeamEngineUpdateArgs is the payload for CmdSolarbeamEngineUpdate: a
// dedicated update command scoped to just the SolarBeam engine product,
// carrying the same integrity fields as UpdateArgs (self-update). It exists
// because the generic CmdInstall path the managed engine scheduler uses
// (rollout/engine.go) is not on the byod_solarbeam capability allowlist —
// installing/updating the engine on a personally-owned device must go
// through a narrower command whose args contain only immutable release
// metadata, never an arbitrary package/executable path or post-install
// command.
type SolarbeamEngineUpdateArgs struct {
	ReleaseID         string `json:"release_id"`
	Version           string `json:"version"`
	URL               string `json:"url"`
	SHA256            string `json:"sha256"`
	SignerFingerprint string `json:"signer_fingerprint"`
	ProductID         string `json:"product_id"`
}

// ShowNotificationArgs is the payload for CmdShowNotification: a native
// OS-level notification (the light agent renders it as a Windows tray
// balloon) shown on the machine itself, distinct from an in-app ReadyApp
// notification. Kind is a deliberately open string identifying the
// notification's purpose ("connection_request" today; future kinds like
// "session_ending" or "update_available" reuse this same command/args
// shape without a proto change) — the agent does not branch on Kind to
// decide whether/how to render, only Severity affects presentation, so a
// caller can introduce a new Kind without an agent release. URL, if set,
// is informational only today (the agent does not yet act on it — no
// click-to-open handler exists); carried so a future one can be added
// without another args change.
type ShowNotificationArgs struct {
	Kind  string `json:"kind"`
	Title string `json:"title"`
	Body  string `json:"body"`
	// Severity is "info" (default when empty), "warning", or "error" —
	// selects the tray balloon's icon style. Unrecognised values fall back
	// to "info" rather than erroring, so a forward-compatible server can
	// send a severity an older agent doesn't know about without breaking it.
	Severity string `json:"severity,omitempty"`
	URL      string `json:"url,omitempty"`
}

// LightInventoryData is the minimal, privacy-safe inventory snapshot a
// byod_solarbeam-profiled agent reports — deliberately a narrow subset of
// InventoryData. Only these six fields may ever appear on the wire for a
// BYOD machine; the server-side ingestion path
// (server/internal/dispatch/dispatch.go's HandleInventory BYOD branch)
// strict-decodes this with json.Decoder.DisallowUnknownFields so an agent
// sending hostname, username, network, or installed_software fails closed
// rather than persisting personal data about someone's home PC.
// TestLightInventoryData_ExactlySixFields (messages_test.go) guards this
// struct against silent drift — adding or renaming a field must touch
// that test deliberately.
type LightInventoryData struct {
	OSFamily         string `json:"os_family"`
	OSMajorVersion   string `json:"os_major_version"`
	Architecture     string `json:"architecture"`
	AgentVersion     string `json:"agent_version"`
	SolarbeamVersion string `json:"solarbeam_version,omitempty"`
	SolarbeamStatus  string `json:"solarbeam_status,omitempty"`
}
